name: gym-http-api
version: '0.1.0.0'
description: Haskell binding for the OpenAi gym API
synopsis: bindings to gym-http-api
category: Web
author: Daniel Lucsanszky, Sam Stites
maintainer: dl3913@ic.ac.uk, sam@stites.io
license: MIT
license-file: LICENSE
github: openai/gym-http-api/binding-hs
extra-source-files:
- README.md

default-extensions:
  - OverloadedStrings

dependencies:
  - exceptions
  - http-client
  - servant-client

library:
  source-dirs: src
  other-modules:
  - OpenAI.Gym.Prelude

  dependencies:
  - base >=4.7 && <5
  - aeson
  - monad-loops
  - unordered-containers
  - servant
  - servant-lucid
  - text
  - transformers

executables:
  example:
    main: Agent.hs
    source-dirs: examples
    dependencies:
    - base >=4.7 && <5
    - gym-http-api

# tests:
  # binding-hs-test:
    # main: Spec.hs
    # source-dirs: test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-K1K
    # dependencies:
    # - base
    # - binding-hs
